"""update table audit

Revision ID: 0ee37f749a7e
Revises: 1fe16fbde0bd
Create Date: 2025-11-24 12:10:41.879956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee37f749a7e'
down_revision: Union[str, Sequence[str], None] = '1fe16fbde0bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('impression', sa.String(length=50), nullable=True),
    sa.Column('printing_time', sa.String(length=50), nullable=True),
    sa.Column('tva', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('montant_tva', sa.Float(), nullable=True),
    sa.Column('montant_ttc', sa.Float(), nullable=True),
    sa.Column('taux_reduction', sa.Float(), nullable=True),
    sa.Column('id_customer', sa.Integer(), nullable=True),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_description'), 'devis', ['description'], unique=False)
    op.create_index(op.f('ix_devis_format'), 'devis', ['format'], unique=False)
    op.create_index(op.f('ix_devis_id'), 'devis', ['id'], unique=False)
    op.create_index(op.f('ix_devis_impression'), 'devis', ['impression'], unique=False)
    op.create_index(op.f('ix_devis_montant_ttc'), 'devis', ['montant_ttc'], unique=False)
    op.create_index(op.f('ix_devis_montant_tva'), 'devis', ['montant_tva'], unique=False)
    op.create_index(op.f('ix_devis_name'), 'devis', ['name'], unique=False)
    op.create_index(op.f('ix_devis_price'), 'devis', ['price'], unique=False)
    op.create_index(op.f('ix_devis_printing_time'), 'devis', ['printing_time'], unique=False)
    op.create_index(op.f('ix_devis_quantity'), 'devis', ['quantity'], unique=False)
    op.create_index(op.f('ix_devis_taux_reduction'), 'devis', ['taux_reduction'], unique=False)
    op.create_index(op.f('ix_devis_tva'), 'devis', ['tva'], unique=False)
    op.add_column('admin_audit', sa.Column('admin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_audit', 'admin')
    op.drop_index(op.f('ix_devis_tva'), table_name='devis')
    op.drop_index(op.f('ix_devis_taux_reduction'), table_name='devis')
    op.drop_index(op.f('ix_devis_quantity'), table_name='devis')
    op.drop_index(op.f('ix_devis_printing_time'), table_name='devis')
    op.drop_index(op.f('ix_devis_price'), table_name='devis')
    op.drop_index(op.f('ix_devis_name'), table_name='devis')
    op.drop_index(op.f('ix_devis_montant_tva'), table_name='devis')
    op.drop_index(op.f('ix_devis_montant_ttc'), table_name='devis')
    op.drop_index(op.f('ix_devis_impression'), table_name='devis')
    op.drop_index(op.f('ix_devis_id'), table_name='devis')
    op.drop_index(op.f('ix_devis_format'), table_name='devis')
    op.drop_index(op.f('ix_devis_description'), table_name='devis')
    op.drop_table('devis')
    # ### end Alembic commands ###
