"""modification de la table customers (proprietes unique retire sur conty, city, company)

Revision ID: 1e67695fb083
Revises: ecc62468796f
Create Date: 2025-11-21 10:34:49.703248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e67695fb083'
down_revision: Union[str, Sequence[str], None] = 'ecc62468796f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.drop_index(op.f('ix_customers_company'), table_name='customers')
    op.create_index(op.f('ix_customers_company'), 'customers', ['company'], unique=False)
    op.drop_index(op.f('ix_customers_country'), table_name='customers')
    op.create_index(op.f('ix_customers_country'), 'customers', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_country'), table_name='customers')
    op.create_index(op.f('ix_customers_country'), 'customers', ['country'], unique=True)
    op.drop_index(op.f('ix_customers_company'), table_name='customers')
    op.create_index(op.f('ix_customers_company'), 'customers', ['company'], unique=True)
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=True)
    # ### end Alembic commands ###
