"""ajout status dans table devis

Revision ID: 1f5dd0e21703
Revises: 52113549a9b3
Create Date: 2025-12-13 18:00:38.392412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5dd0e21703'
down_revision: Union[str, Sequence[str], None] = '52113549a9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('status', sa.String(length=15), nullable=True))
    op.add_column('devis_deleted', sa.Column('status', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devis_deleted', 'status')
    op.drop_column('devis', 'status')
    # ### end Alembic commands ###
