"""add productprintingdeleted

Revision ID: 5ccad23f9b68
Revises: 0db2fb310c75
Create Date: 2025-11-26 12:13:30.085370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ccad23f9b68'
down_revision: Union[str, Sequence[str], None] = '0db2fb310c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_printing_deleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=255), nullable=True),
    sa.Column('papier_grammage', sa.String(length=255), nullable=True),
    sa.Column('finition', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('front_price', sa.Float(), nullable=True),
    sa.Column('back_price', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_printing_deleted_original_id'), 'product_printing_deleted', ['original_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_printing_deleted_original_id'), table_name='product_printing_deleted')
    op.drop_table('product_printing_deleted')
    # ### end Alembic commands ###
