"""ajout colonne deleted_cascade dans devisdeleted

Revision ID: 5d2d2b477397
Revises: d35bf690041a
Create Date: 2026-01-08 15:41:35.751231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2d2b477397'
down_revision: Union[str, Sequence[str], None] = 'd35bf690041a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis_deleted', sa.Column('deleted_cascade', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devis_deleted', 'deleted_cascade')
    # ### end Alembic commands ###
