"""modification ajout de id_product 

Revision ID: 5f0c7fe386b0
Revises: 8d06487a94dd
Create Date: 2025-12-11 16:30:27.209372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0c7fe386b0'
down_revision: Union[str, Sequence[str], None] = '8d06487a94dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('id_product', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_devis_id_product'), 'devis', ['id_product'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devis_id_product'), table_name='devis')
    op.drop_column('devis', 'id_product')
    # ### end Alembic commands ###
