"""ajout table devis deleted

Revision ID: 607dff955446
Revises: c64c2fc569de
Create Date: 2025-12-13 01:17:08.786484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607dff955446'
down_revision: Union[str, Sequence[str], None] = 'c64c2fc569de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devis_deleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('impression', sa.String(length=50), nullable=True),
    sa.Column('printing_time', sa.String(length=50), nullable=True),
    sa.Column('description_devis', sa.String(length=255), nullable=True),
    sa.Column('tva', sa.Float(), nullable=True),
    sa.Column('prix_base', sa.Float(), nullable=True),
    sa.Column('price_taux', sa.Float(), nullable=True),
    sa.Column('montant_tva', sa.Float(), nullable=True),
    sa.Column('montant_ttc', sa.Float(), nullable=True),
    sa.Column('taux_applique', sa.Float(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('id_customer', sa.Integer(), nullable=True),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_deleted_description'), 'devis_deleted', ['description'], unique=False)
    op.create_index(op.f('ix_devis_deleted_description_devis'), 'devis_deleted', ['description_devis'], unique=False)
    op.create_index(op.f('ix_devis_deleted_format'), 'devis_deleted', ['format'], unique=False)
    op.create_index(op.f('ix_devis_deleted_id'), 'devis_deleted', ['id'], unique=False)
    op.create_index(op.f('ix_devis_deleted_id_admin'), 'devis_deleted', ['id_admin'], unique=False)
    op.create_index(op.f('ix_devis_deleted_id_customer'), 'devis_deleted', ['id_customer'], unique=False)
    op.create_index(op.f('ix_devis_deleted_id_product'), 'devis_deleted', ['id_product'], unique=False)
    op.create_index(op.f('ix_devis_deleted_impression'), 'devis_deleted', ['impression'], unique=False)
    op.create_index(op.f('ix_devis_deleted_montant_ttc'), 'devis_deleted', ['montant_ttc'], unique=False)
    op.create_index(op.f('ix_devis_deleted_montant_tva'), 'devis_deleted', ['montant_tva'], unique=False)
    op.create_index(op.f('ix_devis_deleted_name'), 'devis_deleted', ['name'], unique=False)
    op.create_index(op.f('ix_devis_deleted_original_id'), 'devis_deleted', ['original_id'], unique=True)
    op.create_index(op.f('ix_devis_deleted_price_taux'), 'devis_deleted', ['price_taux'], unique=False)
    op.create_index(op.f('ix_devis_deleted_printing_time'), 'devis_deleted', ['printing_time'], unique=False)
    op.create_index(op.f('ix_devis_deleted_prix_base'), 'devis_deleted', ['prix_base'], unique=False)
    op.create_index(op.f('ix_devis_deleted_quantity'), 'devis_deleted', ['quantity'], unique=False)
    op.create_index(op.f('ix_devis_deleted_taux_applique'), 'devis_deleted', ['taux_applique'], unique=False)
    op.create_index(op.f('ix_devis_deleted_tva'), 'devis_deleted', ['tva'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devis_deleted_tva'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_taux_applique'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_quantity'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_prix_base'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_printing_time'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_price_taux'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_original_id'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_name'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_montant_tva'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_montant_ttc'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_impression'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_id_product'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_id_customer'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_id_admin'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_id'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_format'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_description_devis'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_description'), table_name='devis_deleted')
    op.drop_table('devis_deleted')
    # ### end Alembic commands ###
