"""ajout colonne create_at ajuste dans les bd deleted

Revision ID: 61061dde5197
Revises: 5d2d2b477397
Create Date: 2026-01-08 18:39:49.307827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61061dde5197'
down_revision: Union[str, Sequence[str], None] = '5d2d2b477397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_category', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('customer_category_deleted', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customer_category_deleted', sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('customers_deleted', sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('product_printing_deleted', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_printing_deleted', 'created_at')
    op.drop_column('customers_deleted', 'deleted_at')
    op.drop_column('customer_category_deleted', 'deleted_at')
    op.drop_column('customer_category_deleted', 'created_at')
    op.drop_column('customer_category', 'created_at')
    # ### end Alembic commands ###
