"""modification du champs taux_reduction en taux

Revision ID: 73991405b3c9
Revises: becb4e28b432
Create Date: 2025-12-11 11:34:10.613002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73991405b3c9'
down_revision: Union[str, Sequence[str], None] = 'becb4e28b432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('taux_applique', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_devis_taux_reduction'), table_name='devis')
    op.create_index(op.f('ix_devis_taux_applique'), 'devis', ['taux_applique'], unique=False)
    op.drop_column('devis', 'taux_reduction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('taux_reduction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_devis_taux_applique'), table_name='devis')
    op.create_index(op.f('ix_devis_taux_reduction'), 'devis', ['taux_reduction'], unique=False)
    op.drop_column('devis', 'taux_applique')
    # ### end Alembic commands ###
