"""edit table customer category deleted

Revision ID: 8bae51cf7991
Revises: 5f1997fd567f
Create Date: 2025-11-26 15:45:57.121150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bae51cf7991'
down_revision: Union[str, Sequence[str], None] = '5f1997fd567f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_category_deleted', sa.Column('original_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customer_category_deleted_original_id'), 'customer_category_deleted', ['original_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_category_deleted_original_id'), table_name='customer_category_deleted')
    op.drop_column('customer_category_deleted', 'original_id')
    # ### end Alembic commands ###
