"""modification ajout prix base

Revision ID: 8d06487a94dd
Revises: 73991405b3c9
Create Date: 2025-12-11 11:53:09.509481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d06487a94dd'
down_revision: Union[str, Sequence[str], None] = '73991405b3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('prix_base', sa.Float(), nullable=True))
    op.add_column('devis', sa.Column('price_taux', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_devis_price'), table_name='devis')
    op.create_index(op.f('ix_devis_price_taux'), 'devis', ['price_taux'], unique=False)
    op.create_index(op.f('ix_devis_prix_base'), 'devis', ['prix_base'], unique=False)
    op.drop_column('devis', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_devis_prix_base'), table_name='devis')
    op.drop_index(op.f('ix_devis_price_taux'), table_name='devis')
    op.create_index(op.f('ix_devis_price'), 'devis', ['price'], unique=False)
    op.drop_column('devis', 'price_taux')
    op.drop_column('devis', 'prix_base')
    # ### end Alembic commands ###
