"""reset initial

Revision ID: a6035ec22926
Revises: 
Create Date: 2025-12-04 14:40:43.672377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6035ec22926'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_printing', sa.Column('papier_grammage', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('product_printing', sa.Column('peliculage', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('product_printing_deleted', sa.Column('papier_grammage', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('product_printing_deleted', sa.Column('peliculage', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_printing_deleted', 'peliculage')
    op.drop_column('product_printing_deleted', 'papier_grammage')
    op.drop_column('product_printing', 'peliculage')
    op.drop_column('product_printing', 'papier_grammage')
    # ### end Alembic commands ###
