"""update table product column fron_back_price

Revision ID: aa8d53405447
Revises: a6035ec22926
Create Date: 2025-12-04 15:27:43.680546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8d53405447'
down_revision: Union[str, Sequence[str], None] = 'a6035ec22926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_printing', sa.Column('front_back_price', sa.Float(), nullable=True))
    op.add_column('product_printing', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('product_printing', 'back_price')
    op.add_column('product_printing_deleted', sa.Column('front_back_price', sa.Float(), nullable=True))
    op.drop_column('product_printing_deleted', 'back_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_printing_deleted', sa.Column('back_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('product_printing_deleted', 'front_back_price')
    op.add_column('product_printing', sa.Column('back_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('product_printing', 'created_at')
    op.drop_column('product_printing', 'front_back_price')
    # ### end Alembic commands ###
