"""update table delete_admin

Revision ID: b2379bf8702f
Revises: b7056d3b20e5
Create Date: 2025-11-24 17:07:58.016709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2379bf8702f'
down_revision: Union[str, Sequence[str], None] = 'b7056d3b20e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_deleted', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_deleted', 'password')
    # ### end Alembic commands ###
