"""update table audit4

Revision ID: b7056d3b20e5
Revises: f825c65baf01
Create Date: 2025-11-24 16:18:18.670122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7056d3b20e5'
down_revision: Union[str, Sequence[str], None] = 'f825c65baf01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_audit', sa.Column('object_id', sa.Integer(), nullable=True))
    op.drop_column('admin_audit', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_audit', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('admin_audit', 'object_id')
    # ### end Alembic commands ###
