"""mise a jour de la table devis et devis_deleted

Revision ID: ba178b51f07a
Revises: 607dff955446
Create Date: 2025-12-13 01:50:00.660690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba178b51f07a'
down_revision: Union[str, Sequence[str], None] = '607dff955446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('name_product', sa.String(length=50), nullable=True))
    op.add_column('devis', sa.Column('name_customer', sa.String(length=50), nullable=True))
    op.add_column('devis', sa.Column('first_name_customer', sa.String(length=50), nullable=True))
    op.add_column('devis', sa.Column('email_customer', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_devis_name'), table_name='devis')
    op.create_index(op.f('ix_devis_first_name_customer'), 'devis', ['first_name_customer'], unique=False)
    op.create_index(op.f('ix_devis_name_customer'), 'devis', ['name_customer'], unique=False)
    op.create_index(op.f('ix_devis_name_product'), 'devis', ['name_product'], unique=False)
    op.drop_column('devis', 'name')
    op.add_column('devis_deleted', sa.Column('name_customer', sa.String(length=50), nullable=True))
    op.add_column('devis_deleted', sa.Column('first_name_customer', sa.String(length=50), nullable=True))
    op.add_column('devis_deleted', sa.Column('email_customer', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_devis_deleted_first_name_customer'), 'devis_deleted', ['first_name_customer'], unique=False)
    op.create_index(op.f('ix_devis_deleted_name_customer'), 'devis_deleted', ['name_customer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devis_deleted_name_customer'), table_name='devis_deleted')
    op.drop_index(op.f('ix_devis_deleted_first_name_customer'), table_name='devis_deleted')
    op.drop_column('devis_deleted', 'email_customer')
    op.drop_column('devis_deleted', 'first_name_customer')
    op.drop_column('devis_deleted', 'name_customer')
    op.add_column('devis', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_devis_name_product'), table_name='devis')
    op.drop_index(op.f('ix_devis_name_customer'), table_name='devis')
    op.drop_index(op.f('ix_devis_first_name_customer'), table_name='devis')
    op.create_index(op.f('ix_devis_name'), 'devis', ['name'], unique=False)
    op.drop_column('devis', 'email_customer')
    op.drop_column('devis', 'first_name_customer')
    op.drop_column('devis', 'name_customer')
    op.drop_column('devis', 'name_product')
    # ### end Alembic commands ###
