"""initial

Revision ID: becb4e28b432
Revises: 
Create Date: 2025-12-08 13:18:26.201887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'becb4e28b432'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('post', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_email'), 'admin', ['email'], unique=True)
    op.create_index(op.f('ix_admin_first_name'), 'admin', ['first_name'], unique=False)
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_index(op.f('ix_admin_name'), 'admin', ['name'], unique=False)
    op.create_index(op.f('ix_admin_number'), 'admin', ['number'], unique=True)
    op.create_index(op.f('ix_admin_post'), 'admin', ['post'], unique=False)
    op.create_index(op.f('ix_admin_role'), 'admin', ['role'], unique=False)
    op.create_index(op.f('ix_admin_status'), 'admin', ['status'], unique=False)
    op.create_table('admin_deleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('post', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_deleted_original_id'), 'admin_deleted', ['original_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=True),
    sa.Column('performed_by_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer_category_deleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_category_deleted_original_id'), 'customer_category_deleted', ['original_id'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_category'), 'customers', ['category'], unique=False)
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.create_index(op.f('ix_customers_company'), 'customers', ['company'], unique=False)
    op.create_index(op.f('ix_customers_country'), 'customers', ['country'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_first_name'), 'customers', ['first_name'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_number'), 'customers', ['number'], unique=True)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('customers_deleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_deleted_id'), 'customers_deleted', ['id'], unique=False)
    op.create_index(op.f('ix_customers_deleted_original_id'), 'customers_deleted', ['original_id'], unique=True)
    op.create_table('product_printing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=255), nullable=True),
    sa.Column('papier_grammage', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('peliculage', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('finition', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('front_price', sa.Float(), nullable=True),
    sa.Column('front_back_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_printing_color'), 'product_printing', ['color'], unique=False)
    op.create_index(op.f('ix_product_printing_format'), 'product_printing', ['format'], unique=False)
    op.create_index(op.f('ix_product_printing_name'), 'product_printing', ['name'], unique=True)
    op.create_index(op.f('ix_product_printing_quantity'), 'product_printing', ['quantity'], unique=False)
    op.create_table('product_printing_deleted',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=255), nullable=True),
    sa.Column('papier_grammage', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('peliculage', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('finition', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('front_price', sa.Float(), nullable=True),
    sa.Column('front_back_price', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_printing_deleted_original_id'), 'product_printing_deleted', ['original_id'], unique=False)
    op.create_table('devis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('impression', sa.String(length=50), nullable=True),
    sa.Column('printing_time', sa.String(length=50), nullable=True),
    sa.Column('tva', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('montant_tva', sa.Float(), nullable=True),
    sa.Column('montant_ttc', sa.Float(), nullable=True),
    sa.Column('taux_reduction', sa.Float(), nullable=True),
    sa.Column('id_customer', sa.Integer(), nullable=True),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['id_customer'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_description'), 'devis', ['description'], unique=False)
    op.create_index(op.f('ix_devis_format'), 'devis', ['format'], unique=False)
    op.create_index(op.f('ix_devis_id'), 'devis', ['id'], unique=False)
    op.create_index(op.f('ix_devis_impression'), 'devis', ['impression'], unique=False)
    op.create_index(op.f('ix_devis_montant_ttc'), 'devis', ['montant_ttc'], unique=False)
    op.create_index(op.f('ix_devis_montant_tva'), 'devis', ['montant_tva'], unique=False)
    op.create_index(op.f('ix_devis_name'), 'devis', ['name'], unique=False)
    op.create_index(op.f('ix_devis_price'), 'devis', ['price'], unique=False)
    op.create_index(op.f('ix_devis_printing_time'), 'devis', ['printing_time'], unique=False)
    op.create_index(op.f('ix_devis_quantity'), 'devis', ['quantity'], unique=False)
    op.create_index(op.f('ix_devis_taux_reduction'), 'devis', ['taux_reduction'], unique=False)
    op.create_index(op.f('ix_devis_tva'), 'devis', ['tva'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devis_tva'), table_name='devis')
    op.drop_index(op.f('ix_devis_taux_reduction'), table_name='devis')
    op.drop_index(op.f('ix_devis_quantity'), table_name='devis')
    op.drop_index(op.f('ix_devis_printing_time'), table_name='devis')
    op.drop_index(op.f('ix_devis_price'), table_name='devis')
    op.drop_index(op.f('ix_devis_name'), table_name='devis')
    op.drop_index(op.f('ix_devis_montant_tva'), table_name='devis')
    op.drop_index(op.f('ix_devis_montant_ttc'), table_name='devis')
    op.drop_index(op.f('ix_devis_impression'), table_name='devis')
    op.drop_index(op.f('ix_devis_id'), table_name='devis')
    op.drop_index(op.f('ix_devis_format'), table_name='devis')
    op.drop_index(op.f('ix_devis_description'), table_name='devis')
    op.drop_table('devis')
    op.drop_index(op.f('ix_product_printing_deleted_original_id'), table_name='product_printing_deleted')
    op.drop_table('product_printing_deleted')
    op.drop_index(op.f('ix_product_printing_quantity'), table_name='product_printing')
    op.drop_index(op.f('ix_product_printing_name'), table_name='product_printing')
    op.drop_index(op.f('ix_product_printing_format'), table_name='product_printing')
    op.drop_index(op.f('ix_product_printing_color'), table_name='product_printing')
    op.drop_table('product_printing')
    op.drop_index(op.f('ix_customers_deleted_original_id'), table_name='customers_deleted')
    op.drop_index(op.f('ix_customers_deleted_id'), table_name='customers_deleted')
    op.drop_table('customers_deleted')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_first_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_country'), table_name='customers')
    op.drop_index(op.f('ix_customers_company'), table_name='customers')
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.drop_index(op.f('ix_customers_category'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_customer_category_deleted_original_id'), table_name='customer_category_deleted')
    op.drop_table('customer_category_deleted')
    op.drop_table('customer_category')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_admin_deleted_original_id'), table_name='admin_deleted')
    op.drop_table('admin_deleted')
    op.drop_index(op.f('ix_admin_status'), table_name='admin')
    op.drop_index(op.f('ix_admin_role'), table_name='admin')
    op.drop_index(op.f('ix_admin_post'), table_name='admin')
    op.drop_index(op.f('ix_admin_number'), table_name='admin')
    op.drop_index(op.f('ix_admin_name'), table_name='admin')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_index(op.f('ix_admin_first_name'), table_name='admin')
    op.drop_index(op.f('ix_admin_email'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
