"""ajout champps destription_devis

Revision ID: c64c2fc569de
Revises: 5f0c7fe386b0
Create Date: 2025-12-13 00:15:15.029891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64c2fc569de'
down_revision: Union[str, Sequence[str], None] = '5f0c7fe386b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('description_devis', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_devis_description_devis'), 'devis', ['description_devis'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devis_description_devis'), table_name='devis')
    op.drop_column('devis', 'description_devis')
    # ### end Alembic commands ###
