"""ajout colonne deleted_cascade dans la table customerDeleted

Revision ID: d35bf690041a
Revises: 1f5dd0e21703
Create Date: 2026-01-08 15:23:17.476758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35bf690041a'
down_revision: Union[str, Sequence[str], None] = '1f5dd0e21703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers_deleted', sa.Column('deleted_cascade', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers_deleted', 'deleted_cascade')
    # ### end Alembic commands ###
