"""ajout table produit et table categorie

Revision ID: e49d521e900a
Revises: b2379bf8702f
Create Date: 2025-11-25 15:00:31.008523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e49d521e900a'
down_revision: Union[str, Sequence[str], None] = 'b2379bf8702f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_printing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=255), nullable=True),
    sa.Column('papier_grammage', sa.String(length=255), nullable=True),
    sa.Column('finition', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('front_price', sa.Float(), nullable=True),
    sa.Column('back_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_printing_color'), 'product_printing', ['color'], unique=False)
    op.create_index(op.f('ix_product_printing_format'), 'product_printing', ['format'], unique=False)
    op.create_index(op.f('ix_product_printing_name'), 'product_printing', ['name'], unique=True)
    op.create_index(op.f('ix_product_printing_quantity'), 'product_printing', ['quantity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_printing_quantity'), table_name='product_printing')
    op.drop_index(op.f('ix_product_printing_name'), table_name='product_printing')
    op.drop_index(op.f('ix_product_printing_format'), table_name='product_printing')
    op.drop_index(op.f('ix_product_printing_color'), table_name='product_printing')
    op.drop_table('product_printing')
    op.drop_table('customer_category')
    # ### end Alembic commands ###
