"""update table audit3

Revision ID: e6c33cdf973c
Revises: e2e0d193775d
Create Date: 2025-11-24 13:33:41.504619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c33cdf973c'
down_revision: Union[str, Sequence[str], None] = 'e2e0d193775d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_audit', sa.Column('performed_by_email', sa.String(), nullable=True))
    op.drop_column('admin_audit', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_audit', sa.Column('admin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('admin_audit', 'performed_by_email')
    # ### end Alembic commands ###
