"""add devis_ids column to admin

Revision ID: ecc62468796f
Revises: 4729ee99c91e
Create Date: 2025-11-20 11:59:45.448666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecc62468796f'
down_revision: Union[str, Sequence[str], None] = '4729ee99c91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('admin', sa.Column('devis_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.create_index(op.f('ix_admin_role'), 'admin', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_role'), table_name='admin')
    op.drop_column('admin', 'devis_ids')
    op.drop_column('admin', 'role')
    # ### end Alembic commands ###
